import Vue from "vue";
import {
  Cell,
  CellGroup,
  Field,
  Switch,
  Button,
  Popup,
  Picker,
  DropdownMenu,
  DropdownItem,
  TreeSelect,
  Search,
  Checkbox,
  CheckboxGroup,
  Icon,
  Tabbar,
  TabbarItem,
  Grid,
  GridItem,
  PullRefresh,
  Image as VanImage,
  Toast,
  List,
  Tag,
  Col,
  Row,
  Notify,
  Badge,
  Dialog,
  Radio,
  RadioGroup,
  DatetimePicker,
  NavBar,
  Stepper,
  Step,
  Steps,
  Skeleton,
  Empty,
} from "vant";

Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Field);
Vue.use(Switch);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Picker);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(TreeSelect);
Vue.use(Search);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Icon);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(PullRefresh);
Vue.use(VanImage);
Vue.use(Toast);
Vue.use(List);
Vue.use(Tag);
Vue.use(Col);
Vue.use(Row);
Vue.use(Notify);
Vue.use(Badge);
Vue.use(Dialog);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(DatetimePicker);
Vue.use(NavBar);
Vue.use(Stepper);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Skeleton);
Vue.use(Empty);
